'use client'
import './globals.css'
import React from "react";
import { QueryClient, QueryClientProvider, Hydrate } from "react-query";

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  const [queryClient] = React.useState(() => new QueryClient())
  return (
    <html lang="en">
      <body className=" flex items-center justify-center h-[100vh]" >
<QueryClientProvider client={queryClient}>
  
   {children}
   
</QueryClientProvider>     
      </body>
    </html>
  )
}
